---
seed: 42

model:
  architecture: linearNod # options: convNod, convSca, linearNod, linearSca
  num_classes: 10
  pretrained: false

dataset:
  # type: celeba_identities
  type: mnist
  path: /content/data/mnist
  validation_set_size: 0
  image_size: 28

optimizer:
  # Adam:
  #   lr: 0.001
  #   betas: [0.9, 0.999]
  #   weight_decay: 0.0
  SGD:
    lr: 0.001
    momentum: 0.9

lr_scheduler:
  MultiStepLR:
    milestones: [75, 90]
    gamma: 0.1

training:
  # num_epochs: 100
  num_epochs: 1
  # batch_size: 128
  batch_size: 32
  label_smoothing: 0.0
  dataloader_num_workers: 8
  save_path: results/

rtpt:
  experiment_name: Training target classifier
  name_initials: XX

wandb:
  # enable_logging: true
  enable_logging: false
  args:
    project: model_inversion_targets_mnist
    name: SCA_mnist
    save_code: true