---
stylegan_model: Pnp_stylegan3/stylegan2-ada-pytorch/ffhq.pkl
seed: 42
dataset:
  type: celeba_attr
  path: /content/data/celeba

target_model:
  architecture: convNod # options: convNod, convSca
  num_classes: 5
  weights: /content/drive/MyDrive/Masters/PrivacyML/SCA-code-modified/results/convNod_20250712_130645/Classifier_0.6616_no_val.pth
evaluation_model:
  architecture: inception-v3 # architecture of evaluation model
  num_classes: 5 # number of output neurons
  pretrained: true
  # weights: trained_models/facescrub/inception_v3_facescrub.pt # link to weight file

candidates:
  num_candidates: 200
  candidate_search:
    search_space_size: 5000
    center_crop: 800
    resize: 32
    horizontal_flip: true
    batch_size: 1
    truncation_psi: 0.5
    truncation_cutoff: 8

attack:
  batch_size: 1
  num_epochs: 1
  targets: all
  discriminator_loss_weight: 0.0
  single_w: true
  clip: false
  transformations:
    CenterCrop:
      size: 800
    Resize:
      size: 32
      antialias: true
    RandomResizedCrop:
      size: [32, 32]
      scale: [0.9, 1.0]
      ratio: [1.0, 1.0]
      antialias: true

  optimizer:
    Adam:
      lr: 0.005
      weight_decay: 0
      betas: [0.1, 0.1]

final_selection:
  samples_per_target: 50
  approach: transforms
  iterations: 100


wandb:
  enable_logging: false
  wandb_init_args:
    project: model_inversion_attacks
    save_code: true
    name: Attack_CelebA_FFHQ